### ISSUE TITLE
Code network.jl

### ISSUE THREAD

**Issue by CUG-Zhongyu** [DENG-MIT/Biomass.jl#4]
src's network.jl, line 100, it should be sensealg = sense, not sensalg?

**Comment by jiweiqi** [comment]
hi @CUG-Zhongyu , Feel free to make a pull request if you have found that's a better way.

**Comment by Dionysus7777777** [comment]
I also encountered the same issue, and it does seem to be a problem. It could be caused by different versions. I suggest the author mention this in the README.

**Comment by jiweiqi** [comment]
Feel free to make pull request and contribute!
